services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: metatooth
      POSTGRES_USER: metatooth
      POSTGRES_DB: metatooth_development
      PGDATA: /pgdata
    volumes:
      - pgdata:/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metatooth"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
