- hosts: servers

  tasks:
    - name: Sync docker image
      synchronize:
        src: "{{ src_dir }}/timespace_app_latest.tar.gz"
        dest: "{{ deploy_dir }}"

    - name: Load docker image
      ansible.builtin.shell:
        cmd: docker load < timespace_app_latest.tar.gz
        chdir: "{{ deploy_dir }}"

    - name: Stop running container
      ansible.builtin.shell:
        cmd: docker container remove --force ruby-timespace-1

    - name: Run docker image as container
      ansible.builtin.shell:
        cmd: >
          docker run -d
          -p 4000:3000
          --name ruby-timespace-1
          timespace_app:latest

    - name: Install timespace.metatooth.com service
      become: yes
      template:
        src: ./templates/systemd-service.j2
        dest: /etc/systemd/system/com.metatooth.timespace.service
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start timespace.metatooth.com service
      become: yes
      systemd:
        name: com.metatooth.timespace
        state: restarted
        daemon_reload: yes
        enabled: yes

- hosts: balancers

  handlers:
    - name: Restart Nginx
      become: yes
      ansible.builtin.service:
        name: nginx
        state: restarted

  tasks:

  - name: Install timespace.metatooth.com config
    become: yes
    synchronize:
      src: "{{ src_dir }}/nginx.conf"
      dest: /etc/nginx/sites-available/timespace-metatooth-com

  - name: Enable timespace.metatooth.com
    become: yes
    file:
      src: /etc/nginx/sites-available/timespace-metatooth-com
      dest: /etc/nginx/sites-enabled/timespace-metatooth-com
      state: link
    notify: Restart Nginx
